### ISSUE TITLE
Write logs to stdout instead of files

### ISSUE THREAD

**Issue by lukaszraczylo** [ministryofjustice/courtfinder-search#101]
> (...) we could probably set it up to all go to STDOUT. See http://codeinthehole.com/writing/console-logging-to-stdout-in-django/
> -- @mattmb 

After this we can remove '/srv/cleanup' steps from the Dockerfile.

**Comment by richerry** [comment]
Merged and working. If there was a reason for keeping this issue open please re-open it.
